"""baseline_schema

Revision ID: 8a1542a8b20d
Revises: 
Create Date: 2026-04-25 05:03:28.360432
"""
from alembic import op
import sqlalchemy as sa


revision = '8a1542a8b20d'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_mortgage_tranches_id'), 'mortgage_tranches', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mortgage_tranches_id'), table_name='mortgage_tranches')
    # ### end Alembic commands ###
